In [1]:
import numpy as np

In [3]:
age = [23,24,23,24]

age_array = np.array(age)

print(age_array)

type(age_array)

[23 24 23 24]


numpy.ndarray

In [5]:
books = np.array(["Python","R","Java","SAS"])

print(books)
type(books)

['Python' 'R' 'Java' 'SAS']


numpy.ndarray

In [18]:
np.random.random(20)

array([0.711781  , 0.2332999 , 0.47454929, 0.07365933, 0.88981632,
       0.16710433, 0.09139192, 0.39985544, 0.43571966, 0.85590839,
       0.20195479, 0.73608713, 0.11758045, 0.6324766 , 0.87195658,
       0.67362336, 0.61320397, 0.6512999 , 0.49952266, 0.22888049])

In [22]:
np.random.rand(2,3)

array([[0.45383636, 0.64434364, 0.52913138],
       [0.35295124, 0.3738425 , 0.70222637]])

In [20]:
np.random.randn(2,3)  #includes neg values too

array([[-0.64856386,  0.58636511,  0.37917336],
       [ 2.52462014,  0.08361205,  1.50743552]])

In [23]:
np.random.randint(2,10)

8

In [26]:
np.random.randint(20,100,10)

array([28, 41, 87, 21, 34, 81, 36, 31, 86, 77])

In [45]:
arr = np.arange(start = 10, stop = 100,step = 2, dtype = int)

print(arr)

type(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


numpy.ndarray

In [49]:
arr = np.arange(10, 100, 2, int)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
num = np.linspace(start = 1,stop = 100,num = 10,dtype =int)
print(num)

[  1  12  23  34  45  56  67  78  89 100]


In [67]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
matrix=np.empty((3,3),dtype = int)
print(matrix)

[[  1  13  25]
 [ 38  50  62]
 [ 75  87 100]]


In [94]:
matrix=np.empty((3,3),dtype = object)
print(matrix)

[[None None None]
 [None None None]
 [None None None]]


In [97]:
matrix = np.full((3,3),fill_value=11)
matrix

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [107]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [108]:
np.eye(N=5,M=5,k=0) #if k=0 then main diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [109]:
np.eye(N=5,M=5,k=1)  #if k=0 then upper diagonal

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [110]:
np.eye(N=5,M=5,k=-1)  #if k=0 then lower diagonal

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### Array attributes

In [123]:
#Shape

books = np.array([("Python","Data","Scala") , (10,20,30)])
print(books)

print("The shape of the array is ",books.shape)

[['Python' 'Data' 'Scala']
 ['10' '20' '30']]
The shape of the array is  (2, 3)


In [142]:
#Size

print("The size of the array is ",books.size)

The size of the array is  9


In [141]:
#Dtype

books_new = np.array([10,20,30])

print("The datatype of the array is ",books_new.dtype)

The datatype of the array is  int32


In [140]:
books_new = np.array([(10.3,20.5,30),(1,5,7)])

print("The datatype of the array is ",books_new.dtype)

The datatype of the array is  float64


In [139]:
# dimension - ndim

books = np.array([("Python","Data","Scala") , (10,20,30) , (10.3,20.5,30)])
print(books)

print("The dimension of the array is ",books.ndim)

[['Python' 'Data' 'Scala']
 ['10' '20' '30']
 ['10.3' '20.5' '30']]
The dimension of the array is  2


In [138]:
books_new = np.array([10,20,30])

print("The dimension of the array is ",books_new.ndim)

The dimension of the array is  1


## Array Methods

In [150]:
# Reshape

emp = np.array([("Tarun",23),("Vandana",24),("Tejas",23)])
print("Before reshape : \n",emp)
print("\n")
emp_reshaped = emp.reshape(6,1)
print("After reshape : \n",emp_reshaped)

Before reshape : 
 [['Tarun' '23']
 ['Vandana' '24']
 ['Tejas' '23']]


After reshape : 
 [['Tarun']
 ['23']
 ['Vandana']
 ['24']
 ['Tejas']
 ['23']]


## Array indexing & slicing

In [151]:
emp[-1]

array(['Tejas', '23'], dtype='<U11')

In [152]:
emp[1]

array(['Vandana', '24'], dtype='<U11')

In [153]:
emp[::-1]

array([['Tejas', '23'],
       ['Vandana', '24'],
       ['Tarun', '23']], dtype='<U11')

In [155]:
emp[:2]

array([['Tarun', '23'],
       ['Vandana', '24']], dtype='<U11')

In [156]:
emp[0][0]

'Tarun'

In [157]:
emp[1][0]

'Vandana'

In [158]:
emp[2][0]

'Tejas'

In [163]:
arr = np.array([(20,21,22),(23,24,25),(26,27,28)])
print(arr)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [166]:
arr[1:,0:2]

array([[23, 24],
       [26, 27]])

In [169]:
weight = np.array([73,68,55.5,43,92,66])

print("4th and 5th element", weight[3:5])
print('every second element',weight[0::3])
print('Elements before 93',weight[:4])

4th and 5th element [43. 92.]
every second element [73. 43.]
Elements before 93 [73.  68.  55.5 43. ]


In [176]:
age = np.array([(73,68,54),(21,36,19)])

print(age,"\n")

print("Elements from first row first two columns",age[0,0:2])

print("Elements from second row last two columns",age[1,1:])

[[73 68 54]
 [21 36 19]] 

Elements from first row first two columns [73 68]
Elements from second row last two columns [36 19]


## Array Operations

In [179]:
arrr = np.array([3,6,5,4,2,6])

print('Updated',arrr*3)

Updated [ 9 18 15 12  6 18]


In [182]:
m1 = np.array([[1,0,2],[4,-2,3]])
m2 = np.array([[4,0],[2,3],[1,4]])

multi = m1.dot(m2)
print("Matrix multiplication : \n",multi)

Matrix multiplication : 
 [[ 6  8]
 [15  6]]


In [193]:
weight = np.array([7,6,5,4,9,5])

print(np.square(weight))

[49 36 25 16 81 25]


In [197]:
print(np.power(weight,3))

[343 216 125  64 729 125]


In [203]:
emp = np.array([("Tarun",23),("Vathsa",24),("Tejas",23)])

print("original : \n",emp,"\n")

print("Transpose : \n",np.transpose(emp))

original : 
 [['Tarun' '23']
 ['Vathsa' '24']
 ['Tejas' '23']] 

Transpose : 
 [['Tarun' 'Vathsa' 'Tejas']
 ['23' '24' '23']]


In [209]:
age = np.array([7,6,5,4,9,5])
weight = np.array([73,68,55,43,92,66])

emp = np.concatenate([age,weight])

print("Concatenated array : \n",emp)

Concatenated array : 
 [ 7  6  5  4  9  5 73 68 55 43 92 66]


In [216]:
emp1 = np.array([("Tarun",23),("Vathsa",24),("Tejas",23)])
emp2 = np.array([("Vandana",24),("Meghana",23)])

emp_final = np.concatenate([emp1,emp2])

print("Concatenated array : \n",emp_final)

Concatenated array : 
 [['Tarun' '23']
 ['Vathsa' '24']
 ['Tejas' '23']
 ['Vandana' '24']
 ['Meghana' '23']]


In [214]:
print('Flattened array : \n',np.ndarray.flatten(emp_final))

Flattened array : 
 ['Tarun' '23' 'Vathsa' '24' 'Tejas' '23' 'Vandana' '24' 'Meghana' '23']


## Iterating through arrays

In [219]:
books = np.array(["Python","Data","Scala"])

for chapters in books:
    print(chapters)

Python
Data
Scala


In [222]:
books = np.array([("Python","Data","Scala") , (10,20,30) , (10.3,20.5,30)])

print("The dimension of the array is :",books.ndim,"\n")

for data in books:
    print(data)

The dimension of the array is : 2 

['Python' 'Data' 'Scala']
['10' '20' '30']
['10.3' '20.5' '30']


In [226]:
books = np.array([("Python","Data","Scala") , (10,20,30) , (10.3,20.5,30)])

print("The dimension of the array is :",books.ndim,"\n")

for data in books:
    for chapter in data:
        print(chapter)

The dimension of the array is : 2 

Python
Data
Scala
10
20
30
10.3
20.5
30


# Numpy arrays vs Lists (faster)

In [229]:
import numpy as np
import time

size = 1000000

In [236]:
# Lists

list1 = range(size)
list2 = range(size)

InitialTime = time.time()
result = [(a*b) for a,b in zip(list1,list2)]

print("Time taken by Time : ",(time.time() - InitialTime),"seconds")

Time taken by Time :  0.13409805297851562 seconds


In [238]:
# Numpy

list1 = np.arange(size)
list2 = np.arange(size)

InitialTime = time.time()
result = list1 * list2

print("Time taken by Time : ",(time.time() - InitialTime),"seconds")

Time taken by Time :  0.0029468536376953125 seconds
